# fly.toml app configuration file generated for backend-ai-chatbot-solomon on 2025-07-04T14:17:59+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-ai-chatbot-solomon'
primary_region = 'nrt'

[build]

[deploy]
  release_command_timeout = '45m0s'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
